### ISSUE TITLE
Docker Module not Built - Cannot Use without Kube

### ISSUE THREAD

**Issue by Illydth** [CrunchyData/crunchy-watch#43]
The Makefile does not have a build path for building the docker.so module for this container.

Therefor use of attempted use of `CRUNCHY_WATCH_PLATFORM=docker` results in a Seg Fault.

```
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | plugin.Open(/opt/cpm/bin/crunchy-watch/plugins/docker.so): realpath failed
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | panic: runtime error: invalid memory address or nil pointer dereference
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1571ebe]
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    |
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | goroutine 1 [running]:
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | main.loadPlatformModule(0x7ffc0778ae27, 0x6, 0xc4200dbe08, 0x1)
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | 	/home/dwagneradm/buildenv/cdev/src/github.com/crunchydata/crunchy-watch/util.go:42 +0x1de
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | main.main()
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | 	/home/dwagneradm/buildenv/cdev/src/github.com/crunchydata/crunchy-watch/main.go:229 +0x316
```

**Comment by Illydth** [comment]
And adding the following makefile stanza causes the build process to blow up with:

`
modules: kube-module openshift-module docker-module

docker-module:
	@echo "Building Docker module..."
	@go build -buildmode=plugin \
		-o $(BIULD_DIR)/plugins/docker.so \
		-ldflags='-s -w' \
		plugins/docker/*.go
`

go install command-line-arguments: mkdir /plugins/: permission denied
make[2]: *** [docker-module] Error 1

**Comment by davecramer** [comment]
@Illydth you misspelled BUILD_DIR ...

**Comment by abrightwell** [comment]
@Illydth - Thanks for the feedback.

The original intent was to have it work with multiple platforms and environments. Specifically, this is the reason for the 'plugin' architecture to facilitate [extending](https://github.com/CrunchyData/crunchy-watch#extending-crunchy-watch) functionality. Kubernetes was the priority use case, however, docker was initially one of the targets. Unfortunately, it wasn't completed (though PR's are always welcome. ;-) ). In the meantime, I'll push to remove references to 'docker' and will add completing the docker support to the list.

**Comment by Illydth** [comment]
@davecramer Yep, you are 100% correct on the misspelled "Build" in the Makefile.  It still doesn't function however since the docker.so file has no code in it. :)

But yea, the misspelling is most definitely a problem on my part.
